[package]
name = "npvdkg-rs"
version = "0.0.0-alpha"
edition = "2021"

[dependencies]
bls = { package = "bls12_381", version = "0.6.0", features = ["experimental"] }
ff = "0.11"
generic-array = "0.14"
rand_core = "0.6.0"
sha3 = "0.9"
